### ISSUE TITLE
VS Code detects KDE instead of GNOME for password store

### ISSUE THREAD

**Issue by TheOnlyTails** [flathub/com.visualstudio.code#415]
Ever since the last update, something broke which causes VSC to show an error like this at startup:
![image](https://github.com/flathub/com.visualstudio.code/assets/65342367/678db29f-6499-4815-a2f5-ea00a320f700)

This causes me to be forcibly logged out of settings sync. Problem is, I use Gnome and have been using it for months.
![image](https://github.com/flathub/com.visualstudio.code/assets/65342367/ccb24ea1-8562-4edb-9776-f3c42cc9fdb8)

What is going on?

**Comment by SeaDve** [comment]
Adding `"password-store": "gnome-libsecret"` in `argv.json` as a workaround works for me

**Comment by francoism90** [comment]
@SeaDve Where is this file located?

**Comment by SeaDve** [comment]
> @SeaDve Where is this file located?

Run `Preferences: Configure Runtime Arguments ` command

**Comment by francoism90** [comment]
@SeaDve This doesn't work for me, it also gives me `Property password-store is not allowed.`.

**Comment by AlbertoFabbri93** [comment]
I have tried adding both `"password-store": "gnome-libsecret"` and `"password-store": "gnome"` in argv.json but neither works.

**Comment by irfanhakim-as** [comment]
> @SeaDve This doesn't work for me, it also gives me `Property password-store is not allowed.`.

In my case, it had given me the same warning in argv.json but it worked nonetheless.

In any case, try launching VS Code this way first for logging as well as for testing the workaround:

```sh
flatpak run com.visualstudio.code --verbose --vmodule="*/components/os_crypt/*=1" --password-store=gnome-libsecret
```

If the issue is solved, you can proceed to add `"password-store": "gnome-libsecret"` to `argv.json` so the behaviour persists without the additional flag.

If it doesn't, close VS Code and check the logs for errors.

**Comment by AlbertoFabbri93** [comment]
@irfanhakim-as Thank you for the help!

As before, it does not work for me. This is what I found in the log:
```bash
[23:0809/233425.828199:VERBOSE1:key_storage_linux.cc(174)] OSCrypt using Libsecret as backend.
[23:0809/233425.832975:VERBOSE1:key_storage_libsecret.cc(82)] OSCrypt generated a new password.
[23:0809/233425.833799:INFO:CONSOLE(627)] "%cTRACE color: #888 Layout#layout, height: 1048, width: 1920", source: vscode-file://vscode-app/app/extra/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js (627)
[main 2023-08-09T21:34:25.834Z] window#load: window reported ready (id: 1)
[main 2023-08-09T21:34:25.834Z] ElectronURLListener#flush(): flushing URLs
[23:0809/233425.864152:INFO:CONSOLE(627)] "%cTRACE color: #888 [secrets] getting secret for key: secret://vscode.loginAccount", source: vscode-file://vscode-app/app/extra/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js (627)
[23:0809/233425.864483:INFO:CONSOLE(627)] "%cTRACE color: #888 [secrets] no secret found for key: secret://vscode.loginAccount", source: vscode-file://vscode-app/app/extra/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js (627)
[main 2023-08-09T21:34:25.864Z] Going to get password from keytar: vscode.login account
[main 2023-08-09T21:34:25.868Z] Doing get password from keytar: vscode.login account
[main 2023-08-09T21:34:25.869Z] Did not get a password from keytar for account: account
```

**Comment by quocson95** [comment]
In my case, set argv.json ""password-store": "gnome-libsecret"" and install "zypper install gnome-keyring", then vscode work (sync with github)

**Comment by mscharley** [comment]
I'm actually running KDE but ran into this and while the editor tab for `argv.json` complains that password-store isn't a valid property, `"password-store": "gnome-libsecret"` does get picked up and work for connecting to kwallet (and presumably any other libsecret backend) for me. It does seem to use different keys in kwallet now as i had to sign in again, but the new sign in is remembered across restarting vscode.

**Comment by breningham** [comment]
using your command @irfanhakim-as i notice the following issue: 

```
[24:1106/134215.090087:INFO:CONSOLE(630)] "%cTRACE color: #888 ChatService#constructor: Restored 1 persisted sessions", source: vscode-file://vscode-app/app/extra/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js (630)
[24:1106/134215.096507:INFO:CONSOLE(630)] "%cTRACE color: #888 [SecretStorageService] Encryption is available, using persisted storage", source: vscode-file://vscode-app/app/extra/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js (630)
[24:1106/134215.096601:INFO:CONSOLE(630)] "%cTRACE color: #888 [secrets] getting secret for key: secret://{"extensionId":"vscode.github-authentication","key":"github.auth"}", source: vscode-file://vscode-app/app/extra/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js (630)
[24:1106/134215.096658:INFO:CONSOLE(630)] "%cTRACE color: #888 [secrets] decrypting gotten secret for key: secret://{"extensionId":"vscode.github-authentication","key":"github.auth"}", source: vscode-file://vscode-app/app/extra/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js (630)
[main 2023-11-06T13:42:15.096Z] [EncryptionMainService] Decrypting value.
[24:1106/134215.096902:VERBOSE1:os_crypt_linux.cc(238)] Decryption failed
[main 2023-11-06T13:42:15.097Z] Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at D.decrypt (/app/extra/vscode/resources/app/out/vs/code/electron-main/main.js:42:11339)
    at Object.call (/app/extra/vscode/resources/app/out/vs/code/electron-main/main.js:25:4881)
    at I.s (/app/extra/vscode/resources/app/out/vs/code/electron-main/main.js:23:5128)
    at I.q (/app/extra/vscode/resources/app/out/vs/code/electron-main/main.js:23:4644)
    at c.value (/app/extra/vscode/resources/app/out/vs/code/electron-main/main.js:23:4051)
    at w (/app/extra/vscode/resources/app/out/vs/code/electron-main/main.js:18:1913)
    at w.x (/app/extra/vscode/resources/app/out/vs/code/electron-main/main.js:18:1983)
    at w.fire (/app/extra/vscode/resources/app/out/vs/code/electron-main/main.js:18:2199)
    at c.value (/app/extra/vscode/resources/app/out/vs/code/electron-main/main.js:16:38683)
    at w (/app/extra/vscode/resources/app/out/vs/code/electron-main/main.js:18:1913)
    at w.fire (/app/extra/vscode/resources/app/out/vs/code/electron-main/main.js:18:2130)
    at c.value (/app/extra/vscode/resources/app/out/vs/code/electron-main/main.js:16:38878)
    at w (/app/extra/vscode/resources/app/out/vs/code/electron-main/main.js:18:1913)
    at w.fire (/app/extra/vscode/resources/app/out/vs/code/electron-main/main.js:18:2130)
    at Z (/app/extra/vscode/resources/app/out/vs/code/electron-main/main.js:16:41008)
    at IpcMainImpl.f (/app/extra/vscode/resources/app/out/vs/code/electron-main/main.js:19:96477)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88527)
    at WebContents.emit (node:events:513:28)
[24:1106/134215.105346:INFO:CONSOLE(630)] "%c  ERR color: #f33 Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.", source: vscode-file://vscode-app/app/extra/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js (630)
[24:1106/134215.105416:INFO:CONSOLE(630)] "%cTRACE color: #888 [mainThreadSecretState] No password found for:  vscode.github-authentication github.auth", source: vscode-file://vscode-app/app/extra/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js (630)
[24:1106/134215.105472:INFO:CONSOLE(630)] "%cTRACE color: #888 [mainThreadSecretState] Getting old password for vscode.github-authentication extension:  github.auth", source: vscode-file://vscode-app/app/extra/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js (630)
```

seems that it finds the values but fails to decode them for some reason.

**Comment by francoism90** [comment]
Yeah, I'll not click on any of the provided links.

**Comment by OKRUgit** [comment]
дело ваше, отписал тут чтобы навсегда покончить с этой ошибкой, дальше сделаю отделной страничкой

> Да, я не буду нажимать ни на одну из предоставленных ссылок.

**Comment by OKRUgit** [comment]
скажу больше, если почитать что они там пишут
https://code.visualstudio.com/docs/editor/settings-sync#_troubleshooting-keychain-issues
то вы убедитесь слово (рекомендует) звучит странно. Рекомендовано не значит должно быть!!! Скажем по желанию,
Тут же все наоборот, если рекомендовано, значит обязательно!
И тут же: цитирую 
"[### **(рекомендуется) Настройте связку ключей для использования с VS Code**.](https://code.visualstudio.com/docs/editor/settings-sync#_recommended-configure-the-keyring-to-use-with-vs-code)
Вы можете вручную указать VS Code, какой набор ключей использовать, передав флаг password-store. Мы рекомендуем сначала установить [gnome-keyring,](https://wiki.gnome.org/Projects/GnomeKeyring) если у вас его еще нет, а затем запустить VS Code с code --password-store="gnome"."
Ссылка на ресурс-> https://code.visualstudio.com/docs/editor/settings-sync#_other-linux-desktop-environments

Что они там курят (эти микро мягкие)и кто их просит? 
И между всего прочего эти связки все отключат но упрямо их заставляют использовать. Не всртечал ни одного кто ими пользуется и это как то помогало. Кроме постоянного ввода паролей в две прграммы VScode(теперь ) и ранее в chrome , теже вилы!

**Comment by OKRUgit** [comment]
Всё сам справился а вы?
https://yvsik.ru/forum/topic/c%D0%B2%D1%8F%D0%B7%D0%BA%D0%B0-%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%B9/#postid
Читаем последний пост Написано не очень понятно, пока делал писал что было необходимо , чтоб не запутаться.
Но теперь программа больше не требует вводить пароль.
Работает с ключами от GNOME  и чувствует себя спокойно
бумажник KDE в системе отключен.

Только дергается к сайту GitHub, надо на сайте тоже согласиться атоматизировать и все ...

**Comment by nornewman** [comment]
A bit late to the party, but whoever finds this error for visual studio or vscodium, this helped me:

First:
 sudo flatpak override com.vscodium.codium --env=ELECTRON_PASSWORD_STORE=gnome-libsecret

Then:
flatpak override --user \
  --talk-name=org.kde.kwalletd6 \
  com.vscodium.codium
